language: node_js

services:
  - redis-server

before_script:
  - cp web-dapp/test/server/_utils/contract-output.json web-dapp/src/
  - cp web-dapp/test/server/_utils/server-config-private.js web-dapp/
  - npm install redis

script:
  - npm run --prefix=blockchain coverage
  - npm test

after_success:
  - npm run coverage
