env:
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
    modules: true
    experimentalObjectRestSpread: true
