env:
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
parserOptions:
  sourceType: script
plugins:
  - react
  - jsx-a11y
globals:
  describe: false
  xdescribe: false
  it: false
  xit: false
  after: false
  afterAll: false
  afterEach: false
  before: false
  beforeAll: false
  beforeEach: false
  expect: false
rules:
  indent:
    - warn
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - warn
    - single
  comma-dangle:
    - warn
    - always-multiline
  semi:
    - error
    - always
  eqeqeq:
    - error
    - smart
  strict:
    - error
    - safe