env:
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: script
rules:
  indent:
    - warn
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - warn
    - single
  comma-dangle:
    - warn
    - always-multiline
  semi:
    - error
    - always
  eqeqeq:
    - error
    - smart
  strict:
    - error
    - safe
