env:
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: script
globals:
  describe: false
  xdescribe: false
  it: false
  xit: false
  after: false
  afterEach: false
  before: false
  beforeEach: false
rules:
  indent:
    - warn
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - warn
    - single
  semi:
    - error
    - always
  eqeqeq:
    - error
    - always
  strict:
    - error
    - safe
